name: "Robert's Process Documentation"
favicon: null
layout_spectrum: 0.26203203410841525
typography_spectrum: 0.18528750515542924
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.83111481834203
  lightness: 0.7504276770632714
  saturation: 0.7887982756365091
  rhythmicContrast: 0.7294636017177254
purpose: []
